apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: obs-tools
resources:
  - ns.yaml
  - pvc.yaml
  - rbac.yaml
  - obs-tools-links-configmap.yaml
  - web-configmap.yaml
  - web-deploy.yaml
  - web-svc.yaml
  - cron-validate.yaml