apiVersion: v1
kind: ConfigMap
metadata:
  name: obs-tools-links
  namespace: obs-tools
data:
  sections.html: |
    <div class="section">
      <h2>SHARED ZURICH</h2>
      <div class="card-container">
        <div class="card"><a href="https://google.com/">Test: Success</a></div>
        <div class="card"><a href="https://httpbin.org/status/302">Test: Service Unavailable</a></div>
        <div class="card"><a href="https://no-such-domain.abcdef">Test: Not known</a></div>
        <div class="card"><a href="https://expired.badssl.com/">Test: Expired certificate</a></div>
      </div>
    </div>
    <div class="section">
      <h2>SHARED LAUSANNE</h2>
      <div class="card-container">
        <div class="card"><a href="https://postman-echo.com/delay/10">Test: Slow response</a></div>
      </div>
    </div>